//! # DBus interface proxies for: `net.connman.iwd.Device`, `net.connman.iwd.Station`, `net.connman.iwd.SimpleConfiguration`, `net.connman.iwd.DeviceProvisioning`, `net.connman.iwd.StationDiagnostic`
//!
//! This code was generated by `zbus-xmlgen` `3.1.1` from DBus introspection data.
//! Source: `Interface '/net/connman/iwd/2/163' from service 'net.connman.iwd' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!
//! This DBus object implements
//! [standard DBus interfaces](https://dbus.freedesktop.org/doc/dbus-specification.html),
//! (`org.freedesktop.DBus.*`) for which the following zbus proxies can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! …consequently `zbus-xmlgen` did not generate code for the above interfaces.

use zbus::dbus_proxy;

#[dbus_proxy(
    interface = "net.connman.iwd.Device",
    default_service = "net.connman.iwd",
)]
trait Device {
    /// Adapter property
    #[dbus_proxy(property)]
    fn adapter(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Address property
    #[dbus_proxy(property)]
    fn address(&self) -> zbus::Result<String>;

    /// Mode property
    #[dbus_proxy(property)]
    fn mode(&self) -> zbus::Result<String>;
    fn set_mode(&self, value: &str) -> zbus::Result<()>;

    /// Name property
    #[dbus_proxy(property)]
    fn name(&self) -> zbus::Result<String>;

    /// Powered property
    #[dbus_proxy(property)]
    fn powered(&self) -> zbus::Result<bool>;
    fn set_powered(&self, value: bool) -> zbus::Result<()>;
}

#[dbus_proxy(
    interface = "net.connman.iwd.Station",
    default_service = "net.connman.iwd",
)]
trait Station {
    /// ConnectHiddenNetwork method
    fn connect_hidden_network(&self, name: &str) -> zbus::Result<()>;

    /// Disconnect method
    fn disconnect(&self) -> zbus::Result<()>;

    /// GetHiddenAccessPoints method
    fn get_hidden_access_points(&self) -> zbus::Result<Vec<(String, i16, String)>>;

    /// GetOrderedNetworks method
    fn get_ordered_networks(&self) -> zbus::Result<Vec<(zbus::zvariant::OwnedObjectPath, i16)>>;

    /// RegisterSignalLevelAgent method
    fn register_signal_level_agent(
        &self,
        path: &zbus::zvariant::ObjectPath<'_>,
        levels: &[i16],
    ) -> zbus::Result<()>;

    /// Scan method
    fn scan(&self) -> zbus::Result<()>;

    /// UnregisterSignalLevelAgent method
    fn unregister_signal_level_agent(
        &self,
        path: &zbus::zvariant::ObjectPath<'_>,
    ) -> zbus::Result<()>;

    /// ConnectedNetwork property
    #[dbus_proxy(property)]
    fn connected_network(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Scanning property
    #[dbus_proxy(property)]
    fn scanning(&self) -> zbus::Result<bool>;

    /// State property
    #[dbus_proxy(property)]
    fn state(&self) -> zbus::Result<String>;
}

#[dbus_proxy(
    interface = "net.connman.iwd.SimpleConfiguration",
    default_service = "net.connman.iwd",
)]
trait SimpleConfiguration {
    /// Cancel method
    fn cancel(&self) -> zbus::Result<()>;

    /// GeneratePin method
    fn generate_pin(&self) -> zbus::Result<String>;

    /// PushButton method
    fn push_button(&self) -> zbus::Result<()>;

    /// StartPin method
    fn start_pin(&self, pin: &str) -> zbus::Result<()>;
}

#[dbus_proxy(
    interface = "net.connman.iwd.DeviceProvisioning",
    default_service = "net.connman.iwd",
)]
trait DeviceProvisioning {
    /// ConfigureEnrollee method
    fn configure_enrollee(&self, uri: &str) -> zbus::Result<()>;

    /// StartConfigurator method
    fn start_configurator(&self) -> zbus::Result<String>;

    /// StartEnrollee method
    fn start_enrollee(&self) -> zbus::Result<String>;

    /// Stop method
    fn stop(&self) -> zbus::Result<()>;

    /// Role property
    #[dbus_proxy(property)]
    fn role(&self) -> zbus::Result<String>;

    /// Started property
    #[dbus_proxy(property)]
    fn started(&self) -> zbus::Result<bool>;

    /// URI property
    #[dbus_proxy(property, name = "URI")]
    fn uri(&self) -> zbus::Result<String>;
}

#[dbus_proxy(
    interface = "net.connman.iwd.StationDiagnostic",
    default_service = "net.connman.iwd",
)]
trait StationDiagnostic {
    /// GetDiagnostics method
    fn get_diagnostics(
        &self,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;
}
