//! # DBus interface proxy for: `org.freedesktop.network1.Link`
//!
//! This code was generated by `zbus-xmlgen` `3.1.1` from DBus introspection data.
//! Source: `Interface '/org/freedesktop/network1/link/_3233' from service 'org.freedesktop.network1' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!
//! This DBus object implements
//! [standard DBus interfaces](https://dbus.freedesktop.org/doc/dbus-specification.html),
//! (`org.freedesktop.DBus.*`) for which the following zbus proxies can be used:
//!
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! …consequently `zbus-xmlgen` did not generate code for the above interfaces.

use zbus::dbus_proxy;

#[dbus_proxy(
    interface = "org.freedesktop.network1.Link",
    default_service = "org.freedesktop.network1",
    default_path = "/org/freedesktop/network1/link/_3233"
)]
trait Link {
    /// Describe method
    fn describe(&self) -> zbus::Result<String>;

    /// ForceRenew method
    fn force_renew(&self) -> zbus::Result<()>;

    /// Reconfigure method
    fn reconfigure(&self) -> zbus::Result<()>;

    /// Renew method
    fn renew(&self) -> zbus::Result<()>;

    /// RevertDNS method
    #[dbus_proxy(name = "RevertDNS")]
    fn revert_dns(&self) -> zbus::Result<()>;

    /// RevertNTP method
    #[dbus_proxy(name = "RevertNTP")]
    fn revert_ntp(&self) -> zbus::Result<()>;

    /// SetDNS method
    #[dbus_proxy(name = "SetDNS")]
    fn set_dns(&self, addresses: &[(i32, &[u8])]) -> zbus::Result<()>;

    /// SetDNSEx method
    #[dbus_proxy(name = "SetDNSEx")]
    fn set_dnsex(&self, addresses: &[(i32, &[u8], u16, &str)]) -> zbus::Result<()>;

    /// SetDNSOverTLS method
    #[dbus_proxy(name = "SetDNSOverTLS")]
    fn set_dnsover_tls(&self, mode: &str) -> zbus::Result<()>;

    /// SetDNSSEC method
    #[dbus_proxy(name = "SetDNSSEC")]
    fn set_dnssec(&self, mode: &str) -> zbus::Result<()>;

    /// SetDNSSECNegativeTrustAnchors method
    #[dbus_proxy(name = "SetDNSSECNegativeTrustAnchors")]
    fn set_dnssecnegative_trust_anchors(&self, names: &[&str]) -> zbus::Result<()>;

    /// SetDefaultRoute method
    fn set_default_route(&self, enable: bool) -> zbus::Result<()>;

    /// SetDomains method
    fn set_domains(&self, domains: &[(&str, bool)]) -> zbus::Result<()>;

    /// SetLLMNR method
    #[dbus_proxy(name = "SetLLMNR")]
    fn set_llmnr(&self, mode: &str) -> zbus::Result<()>;

    /// SetMulticastDNS method
    #[dbus_proxy(name = "SetMulticastDNS")]
    fn set_multicast_dns(&self, mode: &str) -> zbus::Result<()>;

    /// SetNTP method
    #[dbus_proxy(name = "SetNTP")]
    fn set_ntp(&self, servers: &[&str]) -> zbus::Result<()>;

    /// AddressState property
    #[dbus_proxy(property)]
    fn address_state(&self) -> zbus::Result<String>;

    /// AdministrativeState property
    #[dbus_proxy(property)]
    fn administrative_state(&self) -> zbus::Result<String>;

    /// BitRates property
    #[dbus_proxy(property)]
    fn bit_rates(&self) -> zbus::Result<(u64, u64)>;

    /// CarrierState property
    #[dbus_proxy(property)]
    fn carrier_state(&self) -> zbus::Result<String>;

    /// IPv4AddressState property
    #[dbus_proxy(property, name = "IPv4AddressState")]
    fn ipv4_address_state(&self) -> zbus::Result<String>;

    /// IPv6AddressState property
    #[dbus_proxy(property, name = "IPv6AddressState")]
    fn ipv6_address_state(&self) -> zbus::Result<String>;

    /// OnlineState property
    #[dbus_proxy(property)]
    fn online_state(&self) -> zbus::Result<String>;

    /// OperationalState property
    #[dbus_proxy(property)]
    fn operational_state(&self) -> zbus::Result<String>;
}
